# Generated by Django 5.2.4 on 2025-07-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculator_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_a', models.FloatField()),
                ('number_b', models.FloatField()),
                ('operation', models.CharField(max_length=10)),
                ('operation_status', models.CharField(max_length=10)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'calculator_history',
            },
        ),
    ]
